cities = ['Chennai', 'Bangalore', 'Mumbai', 'Calcutta', 'Delhi']
print(cities)
print(sorted(cities))
print(cities)
cities.reverse()
print(cities)
cities.reverse()
print(cities)
cities.sort()
print(cities)
cities.sort(reverse=True)
print(cities)
